# Generated by Django 4.0.2 on 2022-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=100)),
                ('LongUrl', models.CharField(max_length=1000)),
                ('ShortUrl', models.UUIDField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
