# Generated by Django 4.0.2 on 2022-03-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_remove_url_id_alter_url_shorturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='Owner',
        ),
        migrations.AddField(
            model_name='url',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
